import { GoogleGenAI } from "@google/genai";
import { Location, WeatherInfo, ChatMessage } from "../types";

const NON_RETRYABLE_STATUS = [400, 401, 403, 404];
let isGlobalCooling = false;

// Simple memory cache
const weatherCache = new Map<string, WeatherInfo>();
const DEFAULT_WEATHER: WeatherInfo = { temp: "20°C", condition: "sunny", icon: "sunny", description: "Typical spring weather" };

async function withRetry<T>(fn: () => Promise<T>, retries = 3, delay = 2000): Promise<T> {
  if (isGlobalCooling) {
    throw new Error("API is currently in cooling period.");
  }

  try {
    return await fn();
  } catch (error: any) {
    const errorStr = error?.message || "";
    const status = error?.status || 0;
    
    if (NON_RETRYABLE_STATUS.includes(status)) {
      throw error;
    }

    const isRateLimited = errorStr.includes('429') || errorStr.includes('RESOURCE_EXHAUSTED');
    if (retries > 0) {
      const waitTime = isRateLimited ? delay * 5 : delay;
      await new Promise(resolve => setTimeout(resolve, waitTime));
      return withRetry(fn, retries - 1, delay * 2.5);
    }

    if (isRateLimited) {
      isGlobalCooling = true;
      setTimeout(() => { isGlobalCooling = false; }, 30000);
    }
    throw error;
  }
}

export interface ConciergeOptions {
  userLocation?: Location;
  systemInstruction?: string;
  history?: ChatMessage[];
}

export const enrichTripPlan = async (prompt: string, options: ConciergeOptions = {}) => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // Multi-turn contents: prior history + current user prompt
    const contents = [
      ...(options.history || []).map((m) => ({
        role: (m.role === 'user' ? 'user' : 'model') as 'user' | 'model',
        parts: [{ text: m.content }],
      })),
      { role: 'user' as const, parts: [{ text: prompt }] },
    ];

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents,
      config: {
        ...(options.systemInstruction ? { systemInstruction: options.systemInstruction } : {}),
        tools: [{ googleMaps: {} }, { googleSearch: {} }],
        toolConfig: {
          retrievalConfig: options.userLocation ? {
            latLng: { latitude: options.userLocation.lat, longitude: options.userLocation.lng }
          } : undefined
        }
      },
    });

    return {
      text: response.text || "I couldn't find details for that location.",
      grounding: response.candidates?.[0]?.groundingMetadata?.groundingChunks || []
    };
  });
};

export const generateLocationImage = async (promptOrLocation: string): Promise<string> => {
  return withRetry(async () => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Check if the input is already a detailed prompt or just a location name.
    // We want to force a specific style for consistent high-quality results.
    let finalPrompt = promptOrLocation;
    if (promptOrLocation.length < 100) {
        finalPrompt = `A highly detailed, cinematic, and photorealistic travel photograph of ${promptOrLocation}. Golden hour lighting, majestic composition, 4k resolution. The image should capture the essence of the location perfectly without any text overlays.`;
    }
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ text: finalPrompt }] },
      config: {
        imageConfig: { aspectRatio: "4:3" }
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by Gemini");
  });
};

export const getWeatherForecast = async (location: string, date: string): Promise<WeatherInfo | null> => {
  const cacheKey = `${location}-${date}`;
  if (weatherCache.has(cacheKey)) return weatherCache.get(cacheKey)!;

  try {
    return await withRetry(async () => {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const prompt = `What is the typical weather for ${location}, Italy on ${date}? Return JSON: {"temp": "22°C", "condition": "sunny", "icon": "sunny", "description": "Mild"}.`;
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt
      });

      const jsonStr = response.text?.match(/\{[\s\S]*\}/)?.[0];
      if (!jsonStr) throw new Error("Invalid JSON from model");

      let data: WeatherInfo;
      try {
        data = JSON.parse(jsonStr) as WeatherInfo;
      } catch {
        console.warn("Weather JSON parse failed, using fallback");
        data = { ...DEFAULT_WEATHER };
      }
      if (!data.temp || !data.icon) {
        data = { ...DEFAULT_WEATHER, ...data };
      }
      weatherCache.set(cacheKey, data);
      return data;
    });
  } catch (e) {
    console.warn("Weather fetch failed:", e);
    return null;
  }
};